//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using System;
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;

namespace Assembly_CSharp.Generated
{
    [BurstCompile]
    public struct DashGhostComponentSerializer
    {
        static DashGhostComponentSerializer()
        {
            State = new GhostComponentSerializer.State
            {
                GhostFieldsHash = 8970840532993740884,
                ExcludeFromComponentCollectionHash = 0,
                ComponentType = ComponentType.ReadWrite<Dash>(),
                ComponentSize = UnsafeUtility.SizeOf<Dash>(),
                SnapshotSize = UnsafeUtility.SizeOf<Snapshot>(),
                ChangeMaskBits = ChangeMaskBits,
                SendMask = GhostComponentSerializer.SendMask.Interpolated | GhostComponentSerializer.SendMask.Predicted,
                SendForChildEntities = 1,
                CopyToSnapshot =
                    new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyToSnapshot),
                CopyFromSnapshot =
                    new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyFromSnapshot),
                RestoreFromBackup =
                    new PortableFunctionPointer<GhostComponentSerializer.RestoreFromBackupDelegate>(RestoreFromBackup),
                PredictDelta = new PortableFunctionPointer<GhostComponentSerializer.PredictDeltaDelegate>(PredictDelta),
                CalculateChangeMask =
                    new PortableFunctionPointer<GhostComponentSerializer.CalculateChangeMaskDelegate>(
                        CalculateChangeMask),
                Serialize = new PortableFunctionPointer<GhostComponentSerializer.SerializeDelegate>(Serialize),
                Deserialize = new PortableFunctionPointer<GhostComponentSerializer.DeserializeDelegate>(Deserialize),
                #if UNITY_EDITOR || DEVELOPMENT_BUILD
                ReportPredictionErrors = new PortableFunctionPointer<GhostComponentSerializer.ReportPredictionErrorsDelegate>(ReportPredictionErrors),
                #endif
            };
            #if UNITY_EDITOR || DEVELOPMENT_BUILD
            State.NumPredictionErrorNames = GetPredictionErrorNames(ref State.PredictionErrorNames);
            #endif
        }
        public static readonly GhostComponentSerializer.State State;
        public struct Snapshot
        {
            public int distance_traveled;
            public int max_distance;
            public int speed;
            public int dir_x;
            public int dir_y;
            public int dir_z;
        }
        public const int ChangeMaskBits = 4;
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyToSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData, snapshotOffset + snapshotStride*i);
                ref var component = ref GhostComponentSerializer.TypeCast<Dash>(componentData, componentStride*i);
                ref var serializerState = ref GhostComponentSerializer.TypeCast<GhostSerializerState>(stateData, 0);
                snapshot.distance_traveled = (int) math.round(component.distance_traveled * 1000);
                snapshot.max_distance = (int) math.round(component.max_distance * 1000);
                snapshot.speed = (int) math.round(component.speed * 1000);
                snapshot.dir_x = (int) math.round(component.dir.x * 1000);
                snapshot.dir_y = (int) math.round(component.dir.y * 1000);
                snapshot.dir_z = (int) math.round(component.dir.z * 1000);
            }
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyFromSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                ref var snapshotInterpolationData = ref GhostComponentSerializer.TypeCast<SnapshotData.DataAtTick>(snapshotData, snapshotStride*i);
                ref var snapshotBefore = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotBefore, snapshotOffset);
                ref var snapshotAfter = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotAfter, snapshotOffset);
                float snapshotInterpolationFactor = snapshotInterpolationData.InterpolationFactor;
                ref var component = ref GhostComponentSerializer.TypeCast<Dash>(componentData, componentStride*i);
                var deserializerState = GhostComponentSerializer.TypeCast<GhostDeserializerState>(stateData, 0);
                deserializerState.SnapshotTick = snapshotInterpolationData.Tick;
                component.distance_traveled = snapshotBefore.distance_traveled * 0.001f;
                component.max_distance = snapshotBefore.max_distance * 0.001f;
                component.speed = snapshotBefore.speed * 0.001f;
                component.dir = new float3(snapshotBefore.dir_x * 0.001f, snapshotBefore.dir_y * 0.001f, snapshotBefore.dir_z * 0.001f);
            }
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.RestoreFromBackupDelegate))]
        private static void RestoreFromBackup(IntPtr componentData, IntPtr backupData)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<Dash>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<Dash>(backupData, 0);
            component.distance_traveled = backup.distance_traveled;
            component.max_distance = backup.max_distance;
            component.speed = backup.speed;
            component.dir.x = backup.dir.x;
            component.dir.y = backup.dir.y;
            component.dir.z = backup.dir.z;
        }

        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.PredictDeltaDelegate))]
        private static void PredictDelta(IntPtr snapshotData, IntPtr baseline1Data, IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline1 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1Data);
            ref var baseline2 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2Data);
            snapshot.distance_traveled = predictor.PredictInt(snapshot.distance_traveled, baseline1.distance_traveled, baseline2.distance_traveled);
            snapshot.max_distance = predictor.PredictInt(snapshot.max_distance, baseline1.max_distance, baseline2.max_distance);
            snapshot.speed = predictor.PredictInt(snapshot.speed, baseline1.speed, baseline2.speed);
            snapshot.dir_x = predictor.PredictInt(snapshot.dir_x, baseline1.dir_x, baseline2.dir_x);
            snapshot.dir_y = predictor.PredictInt(snapshot.dir_y, baseline1.dir_y, baseline2.dir_y);
            snapshot.dir_z = predictor.PredictInt(snapshot.dir_z, baseline1.dir_z, baseline2.dir_z);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CalculateChangeMaskDelegate))]
        private static void CalculateChangeMask(IntPtr snapshotData, IntPtr baselineData, IntPtr bits, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask;
            changeMask = (snapshot.distance_traveled != baseline.distance_traveled) ? 1u : 0;
            changeMask |= (snapshot.max_distance != baseline.max_distance) ? (1u<<1) : 0;
            changeMask |= (snapshot.speed != baseline.speed) ? (1u<<2) : 0;
            changeMask |= (snapshot.dir_x != baseline.dir_x) ? (1u<<3) : 0;
            changeMask |= (snapshot.dir_y != baseline.dir_y) ? (1u<<3) : 0;
            changeMask |= (snapshot.dir_z != baseline.dir_z) ? (1u<<3) : 0;
            GhostComponentSerializer.CopyToChangeMask(bits, changeMask, startOffset, 4);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void Serialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamWriter writer, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.distance_traveled, baseline.distance_traveled, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.max_distance, baseline.max_distance, compressionModel);
            if ((changeMask & (1 << 2)) != 0)
                writer.WritePackedIntDelta(snapshot.speed, baseline.speed, compressionModel);
            if ((changeMask & (1 << 3)) != 0)
                writer.WritePackedIntDelta(snapshot.dir_x, baseline.dir_x, compressionModel);
            if ((changeMask & (1 << 3)) != 0)
                writer.WritePackedIntDelta(snapshot.dir_y, baseline.dir_y, compressionModel);
            if ((changeMask & (1 << 3)) != 0)
                writer.WritePackedIntDelta(snapshot.dir_z, baseline.dir_z, compressionModel);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.DeserializeDelegate))]
        private static void Deserialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamReader reader, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                snapshot.distance_traveled = reader.ReadPackedIntDelta(baseline.distance_traveled, compressionModel);
            else
                snapshot.distance_traveled = baseline.distance_traveled;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.max_distance = reader.ReadPackedIntDelta(baseline.max_distance, compressionModel);
            else
                snapshot.max_distance = baseline.max_distance;
            if ((changeMask & (1 << 2)) != 0)
                snapshot.speed = reader.ReadPackedIntDelta(baseline.speed, compressionModel);
            else
                snapshot.speed = baseline.speed;
            if ((changeMask & (1 << 3)) != 0)
                snapshot.dir_x = reader.ReadPackedIntDelta(baseline.dir_x, compressionModel);
            else
                snapshot.dir_x = baseline.dir_x;
            if ((changeMask & (1 << 3)) != 0)
                snapshot.dir_y = reader.ReadPackedIntDelta(baseline.dir_y, compressionModel);
            else
                snapshot.dir_y = baseline.dir_y;
            if ((changeMask & (1 << 3)) != 0)
                snapshot.dir_z = reader.ReadPackedIntDelta(baseline.dir_z, compressionModel);
            else
                snapshot.dir_z = baseline.dir_z;
        }
        #if UNITY_EDITOR || DEVELOPMENT_BUILD
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.ReportPredictionErrorsDelegate))]
        private static void ReportPredictionErrors(IntPtr componentData, IntPtr backupData, ref UnsafeList<float> errors)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<Dash>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<Dash>(backupData, 0);
            int errorIndex = 0;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.distance_traveled - backup.distance_traveled));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.max_distance - backup.max_distance));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.speed - backup.speed));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.distance(component.dir, backup.dir));
            ++errorIndex;
        }
        private static int GetPredictionErrorNames(ref FixedString512 names)
        {
            int nameCount = 0;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("distance_traveled"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("max_distance"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("speed"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("dir"));
            ++nameCount;
            return nameCount;
        }
        #endif
    }
}